import type { DemoWorldstate } from "./types";

export const DEMO_REPLAY_ID = "home-move-fixture-replay-v0";

export const demoWorldstate: DemoWorldstate = {
  world: "Rose’s world",
  project: "Plan our home move",
  revision: "rev-018",
  nodes: [
    {
      id: "project-home-move",
      label: "Plan our home move",
      kind: "project",
      eyebrow: "Active project",
      description: "A coordinated move with a clear budget and traceable decisions.",
      status: { knowledge: "Supported", governance: "Adopted", work: "Running" },
    },
    {
      id: "goal-under-4000",
      label: "Complete the move for less than €4,000",
      kind: "goal",
      parentId: "project-home-move",
      eyebrow: "Goal",
      status: { knowledge: "Supported", governance: "Adopted", work: "Planned" },
    },
    {
      id: "area-schedule",
      label: "Schedule",
      kind: "area",
      parentId: "project-home-move",
      eyebrow: "Area",
      status: { knowledge: "Draft", governance: "Adopted", work: "Planned" },
    },
    {
      id: "area-budget",
      label: "Budget",
      kind: "area",
      parentId: "project-home-move",
      eyebrow: "Area",
      status: { knowledge: "Supported", governance: "Adopted", work: "Running" },
    },
    {
      id: "idea-compare-quotes",
      label: "Compare provider quotes",
      kind: "idea",
      parentId: "area-budget",
      eyebrow: "Suggested update",
      description: "Add a simple moving-cost comparison tool to the local planning page.",
      status: { knowledge: "Draft", governance: "Suggested", work: "Planned" },
    },
    {
      id: "question-storage",
      label: "Compare recurring storage separately?",
      kind: "question",
      parentId: "idea-compare-quotes",
      eyebrow: "Open question",
      status: { knowledge: "Open", governance: "Suggested", work: "Planned" },
    },
    {
      id: "artifact-planning-page",
      label: "Local planning page",
      kind: "artifact",
      parentId: "project-home-move",
      eyebrow: "Artifact",
      status: { knowledge: "Supported", governance: "Restricted", work: "Running" },
    },
    {
      id: "area-providers",
      label: "Providers",
      kind: "area",
      parentId: "project-home-move",
      eyebrow: "Area",
      status: { knowledge: "Draft", governance: "Adopted", work: "Planned" },
    },
    {
      id: "area-packing",
      label: "Packing",
      kind: "area",
      parentId: "project-home-move",
      eyebrow: "Area",
      status: { knowledge: "Draft", governance: "Adopted", work: "Planned" },
    },
  ],
  relations: [
    {
      id: "rel-project-goal",
      source: "project-home-move",
      target: "goal-under-4000",
      label: "pursues",
      posture: "canonical",
    },
    {
      id: "rel-budget-idea",
      source: "area-budget",
      target: "idea-compare-quotes",
      label: "proposed home",
      posture: "proposed",
    },
    {
      id: "rel-idea-goal",
      source: "idea-compare-quotes",
      target: "goal-under-4000",
      label: "supports",
      posture: "proposed",
    },
    {
      id: "rel-idea-artifact",
      source: "idea-compare-quotes",
      target: "artifact-planning-page",
      label: "changes",
      posture: "proposed",
    },
    {
      id: "rel-source-idea",
      source: "source-idea",
      target: "idea-compare-quotes",
      label: "interpreted as",
      posture: "evidence",
    },
  ],
  events: [
    {
      id: "event-project",
      kind: "revision",
      label: "Project baseline adopted",
      detail: "Goal, areas, and local planning artifact entered the canonical worldstate.",
      time: "09:14",
      revision: "rev-012",
    },
    {
      id: "event-source",
      kind: "source",
      label: "Idea captured",
      detail: "“Ask Codex to add a simple moving-cost comparison tool to my relocation project.”",
      time: "09:21",
    },
    {
      id: "event-placement",
      kind: "evidence",
      label: "Placement suggested",
      detail: "Budget → Compare provider quotes, with one open storage-cost question.",
      time: "09:21",
      revision: "rev-018",
    },
    {
      id: "event-worker",
      kind: "worker",
      label: "Fixture replay available",
      detail: "A deterministic fixture result is ready after the semantic update and brief are approved.",
      time: "09:24",
      revision: "rev-018",
    },
  ],
};
